# Generated by Django 5.1 on 2024-08-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantSystem", "0001_initial"),
        ("userSystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="restaurants",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to="restaurantSystem.restaurant"
            ),
        ),
    ]
