# Generated by Django 5.1 on 2024-08-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantSystem", "0001_initial"),
        ("userSystem", "0003_alter_employee_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="profile",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="userSystem.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="employee",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="restaurantSystem.restaurant",
            ),
        ),
    ]
