# Generated by Django 5.1 on 2024-08-27 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menuSystem", "0005_alter_menu_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menuSystem.item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalPrice", models.FloatField()),
                ("name", models.CharField(default=None, max_length=100, null=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "item",
                    models.ManyToManyField(
                        blank=True, related_name="orders", to="orderSystem.orderrow"
                    ),
                ),
            ],
        ),
    ]
