# Generated by Django 5.1 on 2024-08-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderSystem", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="item",
            new_name="items",
        ),
    ]
