# Generated by Django 5.1 on 2024-08-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderSystem", "0002_rename_item_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
