# Generated by Django 5.1 on 2024-08-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurantSystem", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="opening_hours",
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
