# Generated by Django 5.1 on 2024-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0007_remove_menu_restaurant"),
        ("restaurantSystem", "0002_alter_restaurant_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menus",
            field=models.ManyToManyField(
                related_name="restaurants", to="menuSystem.menu"
            ),
        ),
    ]
