# Generated by Django 5.1 on 2024-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0002_menu_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, default=True, null=True),
        ),
    ]
