# Generated by Django 5.1 on 2024-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0003_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
