# Generated by Django 5.1 on 2024-08-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0004_alter_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
