# Generated by Django 5.1 on 2024-08-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0005_alter_menu_name"),
        ("restaurantSystem", "0002_alter_restaurant_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="menuSystem.item"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="restaurantSystem.restaurant",
            ),
        ),
    ]
