# Generated by Django 5.1 on 2024-08-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menuSystem", "0006_alter_menu_items_alter_menu_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="restaurant",
        ),
    ]
