# Generated by Django 5.1 on 2024-08-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentSystem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                default="Paid",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
